### ISSUE TITLE
Incorrect request made to Bitbucket Server API

### ISSUE THREAD

**Issue by lbroglio1** [jfrog/frogbot#405] opened 2023-07-28 22:28 UTC
### Describe the bug

When running the scan-pull-requests command and the frogbot program version 2.11.1 tries to download a repository using the Bitbucket Server API it will always fail. Reading the error message shows that frogbot is making a request to the API using the wrong URL. 

Correct requests to the Bitbucket API should look like this
`{BASE_URL}/rest/api/1.0/projects/{project_name}/repos/{repo_name}`

Frogbot version 2.11.1 is currently making a request that looks like this 
`{BASE_URL}/rest/api/1.0/projects/repos/{repo_name}`

[Link to the relevant section of the Bitbucket Server API Documentation](https://developer.atlassian.com/server/bitbucket/rest/v811/api-group-project/#api-api-latest-projects-projectkey-repos-repositoryslug-get)

### Current behavior

When Frogbot makes a request to the Bitbucket Server API it will always fail during the process of running the scan-pull-requests command. In the error message it displays the URL that it made a request to 

Correct requests to the Bitbucket API should look like this
`{BASE_URL}/rest/api/1.0/projects/{project_name}/repos/{repo_name}`

Frogbot version 2.11.1 is currently making a request that looks like this 
`{BASE_URL}/rest/api/1.0/projects/repos/{repo_name}`

[Link to the relevant section of the Bitbucket Server API Documentation](https://developer.atlassian.com/server/bitbucket/rest/v811/api-group-project/#api-api-latest-projects-projectkey-repos-repositoryslug-get)

### Screenshot of the error 
![Screenshot 2023-07-28 at 5 24 46 PM](https://github.com/jfrog/frogbot/assets/140857908/62af843c-3475-41a6-9b9b-0d7400a9ea52)

### Reproduction steps

1. Install frogbot verison 2.11.1
2. Configure it to scan pull request for a Bitbucket server repository
3. Run the scan-pull-requests command
4. The command will always fail

### Expected behavior

When the scan-pull-requests command is run and frogbot makes a request to the Bitbucket server API it should make requests in this format.

`{BASE_URL}/rest/api/1.0/projects/{project_name}/repos/{repo_name}`

This should prevent it from failing.

### JFrog Frogbot version

2.11.1

### Package manager info

Gradle, NPM , and PIP

### Git provider

Bitbucket Server

### Operating system type and version

Linux

**Comment by sverdlov93** [comment] 2023-07-29 09:09
Hi @lbroglio1 
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this bug.
Can you please try again with JFROG_CLI_LOG_LEVEL=DEBUG environment variable and provide the full logs?

**Comment by omerzi** [comment] 2023-07-31 09:45
Hi @lbroglio1, the issue has been fixed in Frogbot v2.11.3. Thank you once again for reporting this issue to us. Please let us know if you have any further questions.

**Closed by omerzi** 2023-07-31 09:45 UTC
Labels: bug
